// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("EFConcurrencyModeTest")>]
[<assembly: AssemblyProductAttribute("EFConcurrencyModeTest")>]
[<assembly: AssemblyCopyrightAttribute("wezeku.com")>]
[<assembly: AssemblyDescriptionAttribute("Helper class for unit tests of Entity Framework concurrency mode.")>]
[<assembly: AssemblyVersionAttribute("2.0.3")>]
[<assembly: AssemblyFileVersionAttribute("2.0.3")>]
[<assembly: ComVisibleAttribute(false)>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EFConcurrencyModeTest"
    let [<Literal>] AssemblyProduct = "EFConcurrencyModeTest"
    let [<Literal>] AssemblyCopyright = "wezeku.com"
    let [<Literal>] AssemblyDescription = "Helper class for unit tests of Entity Framework concurrency mode."
    let [<Literal>] AssemblyVersion = "2.0.3"
    let [<Literal>] AssemblyFileVersion = "2.0.3"
    let [<Literal>] ComVisible = false
